// Generated by Leapkit, do not edit this file
// Leapkit took the files in the public folder and
// embedded those to be available in the binary.
package public

import (
	"embed"
)

//go:embed *
var Files embed.FS
